-- Consultations table for Phase 7 Doctor Consultation
CREATE TABLE IF NOT EXISTS `consultations` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `consultation_no` VARCHAR(20) NOT NULL UNIQUE,
    `appointment_id` INT UNSIGNED NULL,
    `queue_id` INT UNSIGNED NULL,
    `patient_id` INT UNSIGNED NOT NULL,
    `doctor_id` INT UNSIGNED NOT NULL,
    `visit_type` ENUM('New', 'Follow-up') NOT NULL DEFAULT 'New',
    `chief_complaint` TEXT NULL,
    `history` TEXT NULL,
    `physical_examination` TEXT NULL,
    `diagnosis` TEXT NULL,
    `doctor_notes` TEXT NULL,
    `follow_up_required` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `follow_up_date` DATE NULL,
    `consultation_status` ENUM('Draft', 'Completed') NOT NULL DEFAULT 'Draft',
    `created_by` INT UNSIGNED NULL,
    `updated_by` INT UNSIGNED NULL,
    `deleted_at` TIMESTAMP NULL DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_consultation_no` (`consultation_no`),
    INDEX `idx_appointment_id` (`appointment_id`),
    INDEX `idx_queue_id` (`queue_id`),
    INDEX `idx_patient_id` (`patient_id`),
    INDEX `idx_doctor_id` (`doctor_id`),
    INDEX `idx_consultation_status` (`consultation_status`),
    INDEX `idx_follow_up_date` (`follow_up_date`),
    INDEX `idx_deleted_at` (`deleted_at`),
    INDEX `idx_created_by` (`created_by`),
    INDEX `idx_patient_doctor_date` (`patient_id`, `doctor_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;